### ISSUE TITLE
No conversation appears when double-clicking on contact name

### ISSUE THREAD

**Issue by jat255** [xmikos/qhangups#14]
I can seemingly connect okay, and the contact list is displayed, but when I try to double-click on a contact to open a chat, I do not see any window appear, and the following output shows up in the terminal:

``` python
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/qhangups/conversationslist.py", line 56, in on_item_activated
    self.controller.open_messages_dialog(item_data)
  File "/usr/lib/python3.4/site-packages/qhangups/__main__.py", line 267, in open_messages_dialog
    self.messages_dialog.set_conv_tab(conv_id, switch=switch)
  File "/usr/lib/python3.4/site-packages/qhangups/conversations.py", line 52, in set_conv_tab
    conv_widget = self.get_conv_widget(conv_id)
  File "/usr/lib/python3.4/site-packages/qhangups/conversations.py", line 44, in get_conv_widget
    conv_widget = QHangupsConversationWidget(self, self.client, conv)
  File "/usr/lib/python3.4/site-packages/qhangups/conversationwidget.py", line 44, in __init__
    self.on_event(event, set_title=False, set_unread=False)
  File "/usr/lib/python3.4/site-packages/qhangups/conversationwidget.py", line 217, in on_event
    self.handle_message(conv_event, user, set_unread=set_unread)
  File "/usr/lib/python3.4/site-packages/qhangups/conversationwidget.py", line 229, in handle_message
    self.add_message(conv_event.timestamp, message_to_html(conv_event),
  File "/usr/lib/python3.4/site-packages/qhangups/utils.py", line 42, in message_to_html
    lines = [segment_to_html(segment) for segment in conv_event.segments]
  File "/usr/lib/python3.4/site-packages/qhangups/utils.py", line 42, in <listcomp>
    lines = [segment_to_html(segment) for segment in conv_event.segments]
  File "/usr/lib/python3.4/site-packages/qhangups/utils.py", line 19, in segment_to_html
    if segment.type_ == hangups.schemas.SegmentType.TEXT:
AttributeError: 'module' object has no attribute 'schemas'
```

**Comment by jat255** [comment]
This is using the AUR package that is available in Arch Linux

**Comment by lord-aerion** [comment]
I'm seeing the same behaviour and errors, using the same AUR package for Arch Linux.

**Comment by xmikos** [comment]
This is incompatibility with newer version of Hangups library (API has changed). I will update QHangups soon (in the mean time you can use it with older version of Hangups).

**Comment by xmikos** [comment]
Sorry that it took that long, I have now merged `pyqt5` branch into master and fixed compatibility with latest Hangups. New QHangups version 1.7.0 should work for you without problems (but now it needs PyQt 5).
