### ISSUE TITLE
Doesn't run on Qt 5.6 in Windows (missing QtWebKit)

### ISSUE THREAD

**Issue by marczellm** [xmikos/qhangups#26]
```
Traceback (most recent call last):
  File "D:\Python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python35\lib\site-packages\qhangups\__main__.py", line 24, in <module
>
    from qhangups.conversations import QHangupsConversations
  File "D:\Python35\lib\site-packages\qhangups\conversations.py", line 3, in <mo
dule>
    from qhangups.conversationwidget import QHangupsConversationWidget
  File "D:\Python35\lib\site-packages\qhangups\conversationwidget.py", line 3, i
n <module>
    from PyQt5 import QtCore, QtGui, QtWidgets, QtWebKitWidgets
ImportError: cannot import name 'QtWebKitWidgets'
```

QtWebKit was removed from Qt 5.6.

**Comment by xmikos** [comment]
QtWebKit in Qt 5.6 can still be installed, it is just not included in standard Qt distribution anymore. E.g. in Arch Linux you can install `qt5-webkit` package.

I can switch to QtWebEngine, but QtWebEngine is _much_ more resource intensive (it eats a lot more memory), which is really not good for simple usecase like displaying messages in IM client :-/

**Comment by marczellm** [comment]
I'm on Windows where installation / compilation of separate binaries is more complicated. Maybe I'll fork QHangups for my own purpose and try QtWebEngine.

**Comment by xmikos** [comment]
If you try it with QtWebEngine and it will work without problems, I can merge it back, just do a pull request. I will have to try it myself, because QtWebKit clearly wouldn't be there forever (I just don't have time to do it right now).

**Comment by marczellm** [comment]
I tried QtWebEngine, but it dropped a lot of APIs including DOM manipulation (I found no clear source on this, but it only seems possible through injected JavaScript), so the migration is nontrivial.

**Comment by thecodrr** [comment]
I ran this: `sudo apt-get install python3-pyqt5.qtwebkit` in terminal and now everything works perfectly.

**Comment by marczellm** [comment]
Unfortunately I cannot do that on Windows.

But I created a pull request with the necessary changes to migrate to QtWebEngine. Unfortunately some APIs were removed, like scrolling or resizing signals.

**Comment by pranav-prakash** [comment]
It might be possible on windows to compile Qt with support for QtWebKit. At least on osx from homebrew there is a flag to do so.
