### ISSUE TITLE
Receiving SyntaxError on call to Asyncio.async

### ISSUE THREAD

**Issue by Evanlec** [xmikos/qhangups#34]
When I attempt to run qhangouts (I'm on Archlinux) I get this:
```
[el@arch64:~/react-assessment]$ qhangups 
Traceback (most recent call last):
  File "/usr/bin/qhangups", line 11, in <module>
    load_entry_point('QHangups==1.8.1', 'gui_scripts', 'qhangups')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/qhangups/__main__.py", line 204
    asyncio.async(
                ^
SyntaxError: invalid syntax
```

Referring to this line: 
https://github.com/xmikos/qhangups/blob/8b1c666a5588b976e00a8b892be880fda0d7f2eb/qhangups/__main__.py#L204

**Comment by keithzg** [comment]
Running into the same issue, on admittedly a weird platform to be trying to run QHangups on: SailfishOS! Running Python 3.7.2, and my traceback looks identical to the one above.

**Comment by felmur** [comment]
Python 3.8.2, running into the same issue.
